### ISSUE TITLE
Unclear setup code

### ISSUE THREAD

**Issue by samuel-crypto** [pvial00/RedDye#5]
The following code near the beginning of the encrypt function is fairly confusing:
```
for (c=0; c < keylen; c++) {
        k[c % keylen] = (k[c % keylen] + key[c % keylen]) & 0xff;
        j = (j + k[c % keylen]) & 0xff; }
    for (c = 0; c < 256; c++) {
        k[c % keylen] = (k[c % keylen] + j) & 0xff;
        j = (j + k[c % keylen] + c) & 0xff; }
    for (c = 0; c < strlen(nonce); c++) {
        k[c % keylen] = (k[c % keylen] + nonce[c]) & 0xff;
        j = (j + k[c % keylen]) & 0xff; }
    for (c = 0; c < 256; c++) {
        k[c % keylen] = (k[c % keylen] + j) & 0xff;
        j = (j + k[c % keylen] + c) & 0xff; }
```
is this an optimized version or some initial key setup?  Would be nice to document it with comments I think ;)

**Comment by pvial00** [comment]
Yes, this is the keysetup that you're looking at here.  The original code had the keysetup run in a separate function.  The reason it was combined was to resolve an issue when using this code as a shared library.  Code comments are coming this week and I'll let you know when I've finished them.

It's not the best presentation but you're welcome to watch the hand cipher overview on youtube.  There will be a second part of out this week as well.

https://www.youtube.com/watch?v=TIfzwFX3utY&t=1s

**Comment by pvial00** [comment]
https://kryptomagik.com/reddye/RedDye%20Stream%20Cipher.pdf  First draft of the paper.  It should suffice for comments.

**Comment by samuel-crypto** [comment]
I have developed a known plaintext attack on RedDye - is this applicable or
would you prefer if only BlueDye (much stronger version) were analyzed?

**Comment by pvial00** [comment]
It's applicable.  I haven't been able to decrypt more than known n bytes.  If you have an attack, let's see it.

**Comment by pvial00** [comment]
You can post in on reddit if you like.  I was thinking to post it on reddit myself after reviewing but by all means, please do so.  Also, if you wouldn't mind creating a separate issue for the attack on github when you do submit it, I'd appreciate it.  Thanks.

**Comment by pvial00** [comment]
@samuel-crypto any update on the attack?

**Comment by samuel-crypto** [comment]
Excuse me I am exceptionally busy, I will post here as soon as I clear up
my schedule for it

On 28 Oct 2018 4:37 PM, "pvial00" <notifications@github.com> wrote:

@samuel-crypto <https://github.com/samuel-crypto> any update on the attack?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pvial00/RedDye/issues/5#issuecomment-433739249>, or mute
the thread

**Comment by pvial00** [comment]
Ok, looking forward to it.

**Comment by pvial00** [comment]
https://www.reddit.com/r/codes/comments/9vf9a3/reddye_attack_contest_250_prize/  You may be interested in this.
