### ISSUE TITLE
Nonce problem

### ISSUE THREAD

**Issue by samuel-allan** [pvial00/RedDye#8]
You have a for loop that runs until `strlen(nonce)`, but if the nonce happens to contain a `0` at a certain position `strlen` will only count until then, this is intended behavior right? If not I suggest defining a standard nonce-length or having it passed as argument.

**Comment by pvial00** [comment]
It's a bug.  Thanks for pointing this out.  I'll pass it as an argument and have that released ASAP.

**Comment by pvial00** [comment]
This issue has been resolved.  keylen and noncelen have been added as arguments.  Latest code contains the fix.
